### ISSUE TITLE
Anonymous processors

### ISSUE THREAD

**Issue by orthoxerox** [topicusoverheid/kamel#3]
Right now an anonymous processor looks like this:

```kotlin
process(Processor { exchange ->
    exchange.getIn().setBody("<reply/>")
})
```

With an extension method it could look like this:

```kotlin
process { 
    getIn().setBody("<reply/>")
}
```

If you don't mind the change, I'll prepare a PR.

**Comment by bdalenoord** [comment]
We'd be happy to accept such a change!

**Comment by orthoxerox** [comment]
Woops, I didn't notice `processExchange`, which does exactly what I wanted:

```
processExchange { 
    input.setBody("<reply/>")
}
```
